### PR TITLE
Split off reals into package coq-fourcolor-reals that is a dependency of coq-fourcolor

### PR DESCRIPTION
**Pull request by palmskog**
As discussed on Zulip. This is a draft until CI details are figured out.

### CODE REVIEW

**Comment by palmskog** [comment]
@proux01 I just copied over `Makefile` boilerplate from Analysis, does it look reasonable to you?

**Comment by palmskog** [comment]
@ybertot any chance for a review here? This follows closely the boilerplate currently used in MathComp-Analysis.

**Comment by ybertot** [comment]
I am essentially happy with the way the implementation is written.  I think it would be good to add some documentation of real package in the README.md file.

**Comment by ybertot** [comment]
I tried to understand where to change the text in the meta.yml file, but I was not able to locate the sources for the building and installing instructions.

**Comment by palmskog** [comment]
> I tried to understand where to change the text in the meta.yml file, but I was not able to locate the sources for the building and installing instructions.

Nothing has changed in meta.yml or the README how the project is built. The "default" `make` action still builds the whole project, and `opam install coq-fourcolor` installs all files. The way this PR is structured, the only differences are in how opam packages are structured.

How do you propose we should document `coq-fourcolor-reals` (beyond the description already in the `.opam` file)? It may be just confusing to people interested in only the Four Color Theorem to mention this package.

**Comment by proux01** [comment]
Can we keep a meta.yml? My understanding was that this only supports single packages (hence the fact we don't use it in mathcomp).

**Comment by ybertot** [comment]
I just wanted to add a sentence of the form : "If you are only interested in the formalization of real numbers, here is the opam directive to install it : <blabla>"  and "if you want to compile from the source here is the make command to apply".

**Comment by palmskog** [comment]
> Can we keep a meta.yml? My understanding was that this only supports single packages (hence the fact we don't use it in mathcomp).

meta.yml is used for much more than just packages. Indeed we can't currently define/generate packaging boilerplate for monorepo projects with multiple packages, but this doesn't prevent using it for `README.md` and so on.

**Comment by palmskog** [comment]
@ybertot see a201fda - does this fit what you had in mind?

**Comment by ybertot** [comment]
@palmskog and @proux01, thank you for your time.

**Comment by palmskog** [comment]
@ybertot to help out Frédéric Blanqui, there still needs to be a release and corresponding opam packages. I can help out if you want (e.g., I can add packages based on a tag).

**Pull request merged**
