### PR TITLE
[ci] Add Travis file.

### PR DESCRIPTION
**Pull request by ejgallego**
This is still not optimal as we are missing math-comp Docker files,
but they will hopefully become ready soon.

### CODE REVIEW

**Comment by ejgallego** [comment]
Link to enable Travis for this repos: https://www.travis-ci.org/math-comp/fourcolor

**Comment by ejgallego** [comment]
Thanks @ggonthier , note that you will have to activate Travis in either:

- https://www.travis-ci.org/math-comp/fourcolor
- https://www.travis-ci.com/math-comp/fourcolor

for this patch to be tested and have effect.

**Comment by ggonthier** [comment]
Done, it’s up and running, and has identified a compatibility issue with Coq 8.7.
But I also see compilation script errors for 8.6 (no +flambda flag) and 8.9.

**Comment by ejgallego** [comment]
Thank you @ggonthier , I will have a look ASAP and try to update the file.

**Pull request merged**
