### PR TITLE
add meta.yml and generate coq-community boilerplate

### PR DESCRIPTION
**Pull request by palmskog**
@ybertot note that to use our templates for generating the README, I had to change the structure a bit. But all information should be preserved (authorship, paper reference, Wikipedia reference, ...).

### CODE REVIEW

**Comment by palmskog** [comment]
@CohenCyril @Zimmi48 any chance of some help to fix the Cachix setup here for Nix? Since we moved the repo, we can no longer access the math-comp Cachix, and will have to switch to the coq-community Cachix, which requires some Nix Toolbox magic.

**Comment by Zimmi48** [comment]
Sure. IIUC this is completely orthogonal to the present PR, so I will do so in another PR.

**Comment by palmskog** [comment]
Fine with me with a separate PR, thanks. Ideally the other PR will be merged before this one, so we rebase here and get a fully green CI.

**Comment by Zimmi48** [comment]
See #39 (may I let you take care of merging it when CI has passed?).

**Comment by palmskog** [comment]
OK, I will take care of merging PRs so we can get fully green on master with the usual coq-community boilerplate.

**Comment by Zimmi48** [comment]
An issue for projects using our templates and CI generated with the Coq Nix Toolbox, like this one, is that we do not get a Nix CI badge in the README...

**Comment by palmskog** [comment]
@Zimmi48 we should probably document this as a deficiency somewhere. But the same problem applies to any other non-template CI solution.

**Pull request merged**
