### PR TITLE
Rename coq-mathcomp-fourcolor.opam to coq-fourcolor.opam

### LINKED ISSUE #28: opam package for mathcomp-1.12
I just noticed that pinning the new opam file locally installs a package called `coq-mathcomp-fourcolor` while the name in the opam-coq-archive has been `coq-fourcolor` for a long time. 

In any event, I just checked and `a72978a10c1eace75c2d7bb37b87f6cf7a7a4d69` (`master` at the time of this writing) is compatible with `mathcomp-1.12` and it would be nice to have a point-release fort this in the opam-coq-archive.

CC: @ybertot

### PR DESCRIPTION
**Pull request by CohenCyril**
This should fix #28

### CODE REVIEW

**Comment by CohenCyril** [comment]
CC @chdoc what did I mess up this time?

**Comment by chdoc** [comment]
This one looks like the culprit to me: https://github.com/math-comp/fourcolor/blob/a72978a10c1eace75c2d7bb37b87f6cf7a7a4d69/.github/workflows/coq-action.yml#L32

Making the point that consistency is hard to get right without templates :grin:

**Comment by CohenCyril** [comment]
> Making the point that consistency is hard to get right without templates

indeed... I just noticed @ybertot released without this fix :cry:

**Comment by ybertot** [comment]
I did see that this change was in the works, I thought about it, and I decided that this naming of the opam file had too little incidence on the good operation of the opam file in the opam-coq-archive to delay action.

**Pull request merged**
